### ISSUE TITLE
Custom Comics Don't Seem To Work

### ISSUE THREAD

**Issue by neuman** [J-CPelletier/webcomix#11]
I spent a few hours trying to get some custom comics to work, just to test out the system, but was unable to get any to work. It's possible that it's my XPATHs, but they work when I test them in chrome. Here's an example: 

webcomix custom --comic_name=EFT --start_url=https://www.bigheadpress.com/eft?page=1 --next_page_xpath=//*[@id="pagewrapper976"]/div[2]/div[4]/a/@href --image_xpath=//*[@id="pagewrapper"]/div[2]/table/tbody/tr/td[1]/div[1]/a/img/@src
Traceback (most recent call last):
  File "/home/neuman/.local/lib/python3.6/site-packages/webcomix/comic.py", line 101, in verify_xpath
    next_link = parsed_html.xpath(next_page)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neuman/.local/bin/webcomix", line 11, in <module>
    sys.exit(cli())
  File "/home/neuman/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/neuman/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/neuman/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/neuman/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/neuman/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/neuman/.local/lib/python3.6/site-packages/webcomix/main.py", line 122, in custom
    comic.comic_image_selector)
  File "/home/neuman/.local/lib/python3.6/site-packages/webcomix/comic.py", line 106, in verify_xpath
    Failed on URL: {}""".format(next_page, image, url))
Exception: 

                    Next page XPath: //*[@id=pagewrapper976]/div[2]/div[4]/a/@href

                    Image XPath: //*[@id=pagewrapper]/div[2]/table/tbody/tr/td[1]/div[1]/a/img/@src

                    Failed on URL: https://www.bigheadpress.com/eft?page=1

Am I doing something wrong?

**Comment by J-CPelletier** [comment]
Sorry for taking a while to respond.

After a bit of research on my part, I've figured that one thing that isn't necessarily made clear in the Readme's examples are that you need to put the xpath in double quotes and the subsequent string values in the xpath expression in single quotes. This way, you would've gotten this:

```
webcomix custom --comic_name=EFT --start_url=https://www.bigheadpress.com/eft?page=1 --next_page_xpath="//*[@id='pagewrapper976']/div[2]/div[4]/a/@href" --image_xpath="//*[@id='pagewrapper']/div[2]/table/tbody/tr/td[1]/div[1]/a/img/@src"
Page 1:
Page URL: https://www.bigheadpress.com/eft?page=1
Image URLs:


Page 2:
Page URL: https://www.bigheadpress.com/eft?page=2
Image URLs:


Page 3:
Page URL: https://www.bigheadpress.com/eft?page=3
Image URLs:


Verify that the links above are correct.
Are you sure you want to proceed? [y/N]:
```

No image seems to be found here, which I agree is wierd considering the XPath works on Chrome. The XPath looks good to me, so this might be a problem with lxml(the html processing library). To make sure the XPath is less fragile, I usually put `//`to go through multiple descendants at a time. This way, I've modified the XPath you've provided to get the images:

`webcomix custom --comic_name=EFT --start_url=https://www.bigheadpress.com/eft?page=1 --next_page_xpath="//*[@id='pagewrapper976']/div[2]/div[4]/a/@href" --image_xpath="//*[@id='pagewrapper']/div[2]/table//tr//div[1]/a/img/@src"`

**Comment by yasahiro-x** [comment]
Similar issue to neuman's. 
XPath works fine in Chrome, but not while running.
The 'custom' function works on some sites, yet breaks on others.

Here's my case:
`C:\Users\yasah>webcomix custom --comic_name=Friends --start_url=http://www.friendstilldeath.com/comics/1644854/page-1/ --next_page_xpath="//*[@id='comic_area_inner']/a/@href" --image_xpath="//*[@id='comic_image']/@src"
Traceback (most recent call last):
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\site-packages\webcomix\comic.py", line 101, in verify_xpath
    next_link = parsed_html.xpath(next_page)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yasah\AppData\Local\Programs\Python\Python37-32\Scripts\webcomix.exe\__main__.py", line 9, in <module>
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\site-packages\webcomix\main.py", line 122, in custom
    comic.comic_image_selector)
  File "c:\users\yasah\appdata\local\programs\python\python37-32\lib\site-packages\webcomix\comic.py", line 106, in verify_xpath
    Failed on URL: {}""".format(next_page, image, url))
Exception:

                    Next page XPath: //*[@id='comic_area_inner']/a/@href

                    Image XPath: //*[@id='comic_image']/@src

                    Failed on URL: http://www.friendstilldeath.com/comics/1644854/page-1/`

If it indeed is lxml library throwing out problems, any idea which cases trigger it?

**Comment by J-CPelletier** [comment]
I've looked into it and found what seems to be the two distinct issues here:

- Chrome changes the content in HTML inspector when some parts are missing but that they can be inferred, which can happen in cases where `<tbody>` is involved(like in the first problem). See [this](https://stackoverflow.com/questions/29462600/why-isnt-this-xpath-working).
- The framework used to scrape all images(Scrapy) doesn't seem to follow redirections when user input is required, which seems to be the case in the second problem. A browser popup opens when first entering the website, asking for confirmation before you can access its content. This popup doesn't seem to happen when you access it afterwards, but this is due to cookies, which aren't used when using `scrapy`. That means you can't access the website's content with the current version of `webcomix`.

A more reliable way to see if your XPath expression correctly is to use `scrapy shell`, which is normally installed upon installing `webcomix`. If not, use `pip install scrapy`.

```
scrapy shell http://www.friendstilldeath.com/comics/1644854/page-1/
response.body --> Get the html from the response
response.xpath("//*[@id='comic_area_inner']/a/@href") --> Test the XPath expression for the next page
response.xpath("//*[@id='comic_image']/@src") --> Test the XPath for the comic image
```
