### ISSUE TITLE
Bug with custom parameters on 3.8.0

### ISSUE THREAD

**Issue by nfowlie** [J-CPelletier/webcomix#79]
It looks like there are some issues with the latest release version of Webcomix.  Below is output from the terminal.

`(pv) [noel@noelarch ~]$ webcomix --version
webcomix, version 3.8.0

(pv) [noel@noelarch ~]$ webcomix custom xkcd --start-url=http://xkcd.com/1/ --end-url=http://xkcd.com/5/ --next-page-xpath="//a[@rel='next']/@href" --image-xpath="//div[@id='comic']//img/@src" --cbz
Traceback (most recent call last):
  File "/home/noel/pv/bin/webcomix", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/noel/pv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noel/pv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/noel/pv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noel/pv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noel/pv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noel/pv/lib/python3.11/site-packages/webcomix/cli.py", line 249, in custom
    validation = comic.verify_xpath()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/noel/pv/lib/python3.11/site-packages/webcomix/comic.py", line 164, in verify_xpath
    verification = worker.start()
                   ^^^^^^^^^^^^^^
  File "/home/noel/pv/lib/python3.11/site-packages/webcomix/scrapy/crawler_worker.py", line 46, in start
    raise result[0]
ValueError: XPath error: Invalid expression in http://xkcd.com/5/
`

**Comment by J-CPelletier** [comment]
Found the issue, I'll be releasing 3.8.1 to fix this.
